version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/sample-app
permissions:
  - object: /home/ubuntu/sample-app
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: before_install.sh
      runas: ubuntu
  AfterInstall:
    - location: after_install.sh
      runas: ubuntu